ETicaret.WebUI/Controllers/FavoritesController.cs
using ECommerce.Core.Entities;
using ECommerce.Service.Abstract;
using ETicaret.WebUI.ExtensionMethods;
using Microsoft.AspNetCore.Mvc;

namespace ETicaret.WebUI.Controllers
{
    public class FavoritesController : Controller
    {

        private readonly IService<Product> _service;

        public FavoritesController(IService<Product> service)
        {
            _service = service;
        }


        public IActionResult Index()
        {
            var favoriler = GetFavorites();
            return View(favoriler);
        }

        //ürün listesini çekme: 

        private List<Product> GetFavorites()
        {
            return HttpContext.Session.GetJson<List<Product>>("GetFavorites") ?? new List<Product>();

        }
        [HttpPost]
        public IActionResult Add(int ProductId)
        {
            var favoriler = GetFavorites();
            var product = _service.Find(ProductId);

            if (product == null)
            {
                return Json(new { success = false, message = "Ürün bulunamadı!" });
            }

            if (!favoriler.Any(x => x.Id == ProductId))
            {
                favoriler.Add(product);
                HttpContext.Session.SetJson("GetFavorites", favoriler);

                return Json(new
                {
                    success = true,
                    message = $"{product.Name} favorilere eklendi!",
                    favoritesCount = favoriler.Count
                });
            }
            else
            {
                return Json(new
                {
                    success = false,
                    message = $"{product.Name} zaten favorilerinizde!"
                });
            }
        }





        public IActionResult Remove(int ProductId)
        {
            var favoriler = GetFavorites();
            var product = _service.Find(ProductId);
            if (product != null && favoriler.Any(x => x.Id == ProductId))
            {
                favoriler.RemoveAll(i=>i.Id == ProductId);
                HttpContext.Session.SetJson("GetFavorites", favoriler);
            }
            return RedirectToAction("Index");
        }

    }
}

ETicaret.WebUI/Views/Favorites/Index.cshtml
@model List<Product>
@{

    ViewBag.Title = "Favorilerim"; 

}



<section class="container my-5">

    <div class="text-center">
        <h1 class="display-4">
            Favorilerim
        </h1>
    </div>
    <div class="row">
        <div class="col-md-8">
        <div class="table-responsive">
                 @if (Model.Any())
                        {
            <table class="table table-hover table-striped">
                <tr>
                    <th ></th>
                     <th>Ürün</th>
                      <th >Fiyat</th>
                      <th></th>
                </tr>
                <tbody>
                            @foreach(var item in Model)
                            {
                                <tr>
                                    <td>
                                       <img src="/Img/Products/@item.Image" height="37" />
                                    </td>
                                    <td>
                                        <a class="nav-link text-dark" href="/Products/Details/@item.Id">
                                            @item.Name
                                        </a>
                                    </td>
                                    <td>
                                        @item.Price.ToString("c")
                                    </td>
                                    <td>
                                        <form asp-action="Remove" asp-controller="Favorites">
                                        <input  type="hidden" name="ProductId" value="@item.Id" />
                                            <button class="btn btn-sm btn-danger" type="submit" >
                                                <i class="bi bi-x-lg"></i>
                                            </button>

                                        </form>
                                    </td>
                                </tr>
                            }
                </tbody>
                    </table>
                }
                else
                {
                    <div class="container my-5">
                        <div class="alert alert-warning">


                            <h3>Favorilerinizde Ürün bulunmamaktadır!</h3>
                        </div>

                    </div>
                }
            </div>

        </div>
    </div>        
</section>